### ISSUE TITLE
sxm-docker repo is wrong incorrect in Github and DockerHub documentation

### ISSUE THREAD

**Issue by kdorff** [AngellusMortis/sxm-docker#3]
I'm running docker version `Docker version 20.10.20, build 9fdeb9c3de2f2d9f5799be373f27b2f9df44609d`.

I'm trying to run sxm-docker. Using the provided example (with appropriate username/password, but I do not believe it is getting that far):

```
% docker run --rm -it \
    -e SXM_USERNAME=username \
    -e SXM_PASSWORD=password \
    -p 9999:9999 \
    sxm:latest

docker: Error response from daemon: pull access denied for sxm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Worth noting that I **have** authenticated with `docker login`:

```
% docker login

Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /home/kevin/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

I've replicated this on VMs on two networks (in two cities). One running Ubuntu and one running Alpine.

Any thoughts or suggestions?

**Comment by kdorff** [comment]
Aaah I couldn't pull your docker image because the documentation on both pages:

* https://hub.docker.com/r/angellusmortis/sxm-player/
* https://github.com/AngellusMortis/sxm-docker

is incorrect. You're examples all indicate to use a repo named `sxm` but, your repo is named `angellusmortis/sxm-player` so all of your current examples on both pages will fail. I'd suggest updating all your examples on the github readme and on the docker hub page to be more like

```
docker run --rm -it \
    -e SXM_USERNAME=username \
    -e SXM_PASSWORD=password \
    -p 8000:9999 \
    angellusmortis/sxm-player:latest
```

and possibly include a `docker-compose.yml` example such as

```
version: '3.7'
services:
  sxm:
    image: angellusmortis/sxm-player:latest
    restart: unless-stopped
    container_name: sxm
    environment:
      - SXM_USERNAME=username
      - SXM_PASSWORD=password
    ports:
      - 8000:9999
```
